In [1]:
import numpy as np
import scipy.stats as stats
import warnings
warnings.filterwarnings('ignore')

In [2]:
conf_94 = stats.t.interval(alpha = 0.94, df = 1999, loc = 200, scale = 30/np.sqrt(2000))
conf_98 = stats.t.interval(alpha = 0.98, df = 1999, loc = 200, scale = 30/np.sqrt(2000))
conf_96 = stats.t.interval(alpha = 0.96, df = 1999, loc = 200, scale = 30/np.sqrt(2000))

In [3]:
#conf_94

(198.7376089443071, 201.2623910556929)

In [4]:
#conf_98

(198.4381860483216, 201.5618139516784)

In [5]:
#conf_96

(198.6214037429732, 201.3785962570268)

In [6]:
np.round(conf_94,3)

array([198.738, 201.262])

In [7]:
np.round(conf_98,3)

array([198.438, 201.562])

In [8]:
np.round(conf_96,3)

array([198.621, 201.379])